spring.application.name=GestionIncidents

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true


# JWT
jwt.secret=Zm9vYmFyYmF6cXV4cXV4cXV4cXV4cXV4cXV4cXV4cXV4cXV4cXV4cXV4cXV4
jwt.expiration=86400000

# Mail
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
spring.jpa.open-in-view=false

# Image upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

spring.profiles.active=dev

# CORS (dev)
cors.allowed-origins=http://localhost:5173,http://localhost:5174,http://localhost:3000
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

